---
- name: Init RPI4 Cluster
  hosts: all
  become: yes
  vars:
    user_admin:
    - { name: "ubuntu", password: "{{ ubuntu_password }}" }
    users_no_admin:
    - { name: "guest", password: "{{ guest_password }}" }

  tasks:
    - name: "Ensure SSHD is running"
      service: 
        name: sshd 
        state: started 
        enabled: yes

    - name: "Create standard user accounts"
      user: 
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
      with_items:
      - "{{ users_no_admin }}"

    - name: "Update password for admin²"
      user: 
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
      with_items:
      - "{{ user_admin }}"

    - name: "Add authorized key for admin"
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', 'files/' + item.name + '_key.pub') }}"
      with_items:
      - "{{ user_admin }}"
      
