---
- name: "Update APT repositories caches"
  apt:
    update_cache: yes
    
- name: "Upgrade installed packages"
  apt:
    upgrade: dist

- name: "Install iputils-ping"
  apt:
    name: iputils-ping
    state: latest
    install_recommends: no

- name: "Remove necessary packages"
  apt:
    autoremove: yes

