---
- name: "Update APT repositories caches"
  apt:
    update_cache: yes
    cache_valid_time: 86400
    
- name: "Upgrade installed packages"
  apt:
    upgrade: dist

- name: "Install packages"
  apt:
    name: 
      - iputils-ping
    state: latest
    install_recommends: no

- name: "Remove unnecessary packages"
  apt:
    autoremove: yes

